### ISSUE TITLE
⚡수정 부탁드립니다^^

### ISSUE THREAD

**Issue by chomyungha51** [woorifisa-service-dev-2nd/backend-1st-transportation#1]
<.jar파일 실행 후 출력되는 문장에 대한 요청>
1번 기능
- 요금을 출력할 때 세 번째 자릿수에 ,를 구분자로 찍어 주세요
- 이름 뒤에 요금을 출력할 때 space말고 tab으로 구분해주세요

3번 기능
- 요금을 출력할 때 세 번째 자릿수에 ,를 구분자로 찍어 주세요
- 교통 수단 이름 뒤에 space말고 tab으로 구분해주세요

<코드에 대한 요청>
- MainApplication에서 파일을 읽어들이는 코드와 실제 프로그램을 실행시키는 코드를 분리해주세요
- /model에 있는 클래스들을 인터페이스나 상속을 통해 구현하도록 수정해주세요

감사합니다🍀

**Comment by sws6641** [comment]
완료.
